Repository umberto-fontanazza/kiruna-explorer, pull requests merged in 2024-11, with the labels that each got.

#53 FE Refactor auth into authContext
  client/src/API/API.ts
  client/src/App.tsx
  client/src/components/Home.tsx
  client/src/components/LoginForm.tsx
  client/src/components/NavHeader.tsx
  client/src/components/Sidebar.tsx
  client/src/context/auth.ts
Labels: enhancement

#67 Fe general fixes
  client/index.html
  client/src/API/API.ts
  client/src/components/Home.tsx
  client/src/components/Map.tsx
  client/src/components/ModalAddDocument.tsx
  client/src/components/ModalAddLinks.tsx
  client/src/components/NavHeader.tsx
  client/src/components/Sidebar.tsx
  client/src/styles/Map.scss
  client/src/styles/ModalAddDocument.scss
  client/src/styles/NavHeader.scss
  client/src/styles/Sidebar.scss
  client/src/utils/interfaces.tsx
Labels: enhancement

#69 Refactor nav header
  client/src/components/NavHeader.tsx
  client/src/styles/NavHeader.scss
  client/src/styles/global.scss
Labels: enhancement

#68 Fe api
  client/src/API/API.ts
  client/src/API/authAPI.ts
  client/src/API/documentAPI.ts
  client/src/API/linkAPI.ts
  client/src/components/Home.tsx
  client/src/components/Sidebar.tsx
  client/src/utils/interfaces.tsx
Labels: enhancement

#70 Add validation to prevent self linking of documents
  server/src/middleware/validation.ts
  server/src/router/linkRouter.ts
  server/test/selfLink.test.ts
Labels: fix

#77 API documentation fix
  API documentation.md
Labels: fix

#99 Add transaction support for link updates and deletions
  server/src/database.ts
  server/src/model/link.ts
Labels: enhancement

#100 Document modal refactor
  client/src/API/documentAPI.ts
  client/src/components/DocumentForm.tsx
  client/src/components/LinksTable.tsx
  client/src/components/Map.tsx
  client/src/components/ModalAddDocument.tsx
  client/src/components/ProgressBar.tsx
  client/src/routes/DocumentsList.tsx
  client/src/routes/Home.tsx
  client/src/styles/App.scss
  client/src/styles/DocumentForm.scss
  client/src/styles/DocumentsList.scss
  client/src/styles/ModalAddDocument.scss
  client/src/utils/interfaces.ts
  client/src/utils/map.ts
Labels: refactor

#106 Updated API documentation
  API documentation.md
Labels: documentation

#107 Front-end - Fullscreen option disabled
  client/src/utils/map.ts
Labels: bug

#110 Ci fix
  .github/workflows/client-pr.yml
  .github/workflows/server-pr.yml
  client/.prettierrc.json
  client/README.md
  client/eslint.config.js
  client/package-lock.json
  client/package.json
  client/src/API/linkAPI.ts
  client/src/components/CardDocument.tsx
  client/src/components/DocumentForm.tsx
  client/src/components/DocumentFormPages/FirstPageModal.tsx
  client/src/components/LinksTable.tsx
  client/src/components/Map.tsx
  client/src/components/SearchBar.tsx
  client/src/context/DocumentFormContext.ts
  client/src/main.tsx
  client/src/providers/AppProvider.tsx
  client/src/providers/DocumentFormProvider.tsx
  client/src/providers/PopupProvider.tsx
  client/src/utils/interfaces.ts
Labels: enhancement

#116 ui/ux fix
  client/src/routes/LoginForm.tsx
  client/src/styles/LoginForm.scss
Labels: fix

#120 Remove out of place router.use
  server/src/index.ts
Labels: fix

#127 Fix missing base64 conversion, fix omit id in GET /uploads/:id
  server/src/model/upload.ts
  server/src/router/uploadRouter.ts
  server/src/validation/uploadSchema.ts
Labels: fix
